project:
  type: website

website:
  title: "grace-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Scientific Writing
      - href: about-me.qmd
        text: About me
      - href: comm-projects.qmd
        text: Communications Work
      - about.qmd

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true

editor: visual

