---
title: "Scientific Writing"
format: html
---


**Comparative Color Stability of Beef and Pork Longissimus Steaks Throughout Extended Aging in Nitrite-Embedded Packaging**

Grace Bryson, Minha Arankuny, Blake Robbins, Megan Eckhardt, Logan Johnson, Morgan Pfeiffer, Gretchen Mafi, Ranjith Ramanathan 

Meat color is a primary factor influencing consumer perceptions of meat product freshness and wholesomeness.  Any deviation from the desirable bright cherry-red color of beef during retail display reduces consumer acceptance and can result in product discard. While postmortem aging is commonly used to improve tenderness and flavor, extended aging negatively impacts color stability. Nitrite-embedded packaging is a potential strategy to enhance color stability by forming nitric oxide myoglobin, producing a bright red color under anaerobic conditions. However, limited research has compared effectiveness of nitrite-embedded packaging across species the effectiveness of nitrite-embedded packaging across species during g periods. Therefore, the objective of this study was to evaluate color stability of longissimus steaks from beef and pork throughout extended aging in nitrite-embedded packaging. Vacuum packaged USDA upper 2/3 Choice beef strip loins and boneless strap off pork loins were collected from commercial processors and stored for 5 days. Following storage, steaks were cut into 1.27 cm steaks (n = 15 beef strip steaks; n=15 pork chops), and vacuum packaged in nitrite-embedded packaging. Steaks were randomly assigned one of three aging periods (7, 40 and 53 days) and held in dark storage at 2 °C. Surface color measurements using a HunterLab MiniScan spectrophotometer and photographs were collected every 5 days. At each aging endpoint, five steaks per species were analyzed for aerobic plate counts. Data were analyzed using the Mixed Procedure of SAS, and considered significance at P \< 0.05. Redness (a\*) of beef decreased over aging period (P \< 0.05), with lowest observed values on days 0, 33, and 40. Pork a\* values decreased across aging period with lowest observed values on days 0, 33, and 40 with less variability (SE = 0.16 v. beef 0.78), leading to increased statistical sensitivity. Beef chroma showed a tendency to decline across aging period (P \< 0.01), and pork chroma decreased significantly across aging period (P \< 0.0001). The 630/580 ratio of beef and pork was affected by storage day (P \< 0.0001), with peak values observed at day 7 followed by steady declines throughout aging period. Beef and pork APC increased from day 0 to 40 (P \< X). While beef and pork redness, chroma, and 630/580 ratios declined across aging period, values stayed within acceptable ranges reported in literature. Nitrite packaging is still a viable option for bright red and reddish-pink colors of beef and pork throughout extended storage to 40 days. However, color decline and APC may be a consideration in determining the length of storage. 
